import { DataTypeHint } from '@/constants/sql/dataType';

/**
 * https://docs.databricks.com/aws/en/sql/language-manual/sql-ref-datatypes
 */
export const DatabricksTypes: DataTypeHint[] = [
  { name: 'ARRAY', primitiveType: 'string' },
  { name: 'BIGINT', primitiveType: 'long' },
  { name: 'BINARY', primitiveType: 'lob' },
  { name: 'BOOLEAN', primitiveType: 'boolean' },
  { name: 'BYTE', primitiveType: 'int' },
  { name: 'CHAR', primitiveType: 'string' },
  { name: 'DATE', primitiveType: 'date' },
  { name: 'DEC', primitiveType: 'decimal' },
  { name: 'DECIMAL', primitiveType: 'decimal' },
  { name: 'DOUBLE', primitiveType: 'double' },
  { name: 'FLOAT', primitiveType: 'float' },
  { name: 'GEOGRAPHY', primitiveType: 'string' },
  { name: 'GEOMETRY', primitiveType: 'string' },
  { name: 'INT', primitiveType: 'int' },
  { name: 'INTEGER', primitiveType: 'int' },
  { name: 'INTERVAL DAY TO HOUR', primitiveType: 'time' },
  { name: 'INTERVAL DAY TO MINUTE', primitiveType: 'time' },
  { name: 'INTERVAL DAY TO SECOND', primitiveType: 'time' },
  { name: 'INTERVAL DAY', primitiveType: 'time' },
  { name: 'INTERVAL HOUR TO MINUTE', primitiveType: 'time' },
  { name: 'INTERVAL HOUR TO SECOND', primitiveType: 'time' },
  { name: 'INTERVAL HOUR', primitiveType: 'time' },
  { name: 'INTERVAL MINUTE TO SECOND', primitiveType: 'time' },
  { name: 'INTERVAL MINUTE', primitiveType: 'time' },
  { name: 'INTERVAL MONTH', primitiveType: 'time' },
  { name: 'INTERVAL SECOND', primitiveType: 'time' },
  { name: 'INTERVAL YEAR TO MONTH', primitiveType: 'time' },
  { name: 'INTERVAL YEAR', primitiveType: 'time' },
  { name: 'INTERVAL', primitiveType: 'time' },
  { name: 'LONG', primitiveType: 'long' },
  { name: 'MAP', primitiveType: 'string' },
  { name: 'NUMERIC', primitiveType: 'decimal' },
  { name: 'OBJECT', primitiveType: 'string' },
  { name: 'REAL', primitiveType: 'float' },
  { name: 'SHORT', primitiveType: 'int' },
  { name: 'SMALLINT', primitiveType: 'int' },
  { name: 'STRING', primitiveType: 'string' },
  { name: 'STRUCT', primitiveType: 'string' },
  { name: 'TIMESTAMP_LTZ', primitiveType: 'dateTime' },
  { name: 'TIMESTAMP_NTZ', primitiveType: 'dateTime' },
  { name: 'TIMESTAMP', primitiveType: 'dateTime' },
  { name: 'TINYINT', primitiveType: 'int' },
  { name: 'VARCHAR', primitiveType: 'string' },
  { name: 'VARIANT', primitiveType: 'string' },
  { name: 'VOID', primitiveType: 'string' },
];
