import { DataTypeHint } from '@/constants/sql/dataType';

/**
 * https://mariadb.com/kb/en/data-types/
 */
export const MariaDBTypes: DataTypeHint[] = [
  { name: 'BIGINT', primitiveType: 'long' },
  { name: 'BINARY', primitiveType: 'string' },
  { name: 'BIT', primitiveType: 'int' },
  { name: 'BLOB', primitiveType: 'lob' },
  { name: 'BOOL', primitiveType: 'boolean' },
  { name: 'BOOLEAN', primitiveType: 'boolean' },
  { name: 'CHAR BYTE', primitiveType: 'string' },
  { name: 'CHAR VARYING', primitiveType: 'string' },
  { name: 'CHAR', primitiveType: 'string' },
  { name: 'CHARACTER VARYING', primitiveType: 'string' },
  { name: 'CHARACTER', primitiveType: 'string' },
  { name: 'CLOB', primitiveType: 'lob' },
  { name: 'DATE', primitiveType: 'date' },
  { name: 'DATETIME', primitiveType: 'dateTime' },
  { name: 'DEC', primitiveType: 'decimal' },
  { name: 'DECIMAL', primitiveType: 'decimal' },
  { name: 'DOUBLE PRECISION', primitiveType: 'double' },
  { name: 'DOUBLE', primitiveType: 'double' },
  { name: 'ENUM', primitiveType: 'string' },
  { name: 'FIXED', primitiveType: 'decimal' },
  { name: 'FLOAT', primitiveType: 'float' },
  { name: 'FLOAT4', primitiveType: 'float' },
  { name: 'FLOAT8', primitiveType: 'double' },
  { name: 'GEOMETRY', primitiveType: 'string' },
  { name: 'GEOMETRYCOLLECTION', primitiveType: 'string' },
  { name: 'INET4', primitiveType: 'string' },
  { name: 'INET6', primitiveType: 'string' },
  { name: 'INT', primitiveType: 'int' },
  { name: 'INT1', primitiveType: 'int' },
  { name: 'INT2', primitiveType: 'int' },
  { name: 'INT3', primitiveType: 'int' },
  { name: 'INT4', primitiveType: 'int' },
  { name: 'INT8', primitiveType: 'long' },
  { name: 'INTEGER', primitiveType: 'int' },
  { name: 'JSON', primitiveType: 'lob' },
  { name: 'LINESTRING', primitiveType: 'string' },
  { name: 'LONG CHAR VARYING', primitiveType: 'lob' },
  { name: 'LONG CHARACTER VARYING', primitiveType: 'lob' },
  { name: 'LONG VARBINARY', primitiveType: 'lob' },
  { name: 'LONG VARCHAR', primitiveType: 'lob' },
  { name: 'LONG VARCHARACTER', primitiveType: 'lob' },
  { name: 'LONG', primitiveType: 'lob' },
  { name: 'LONGBLOB', primitiveType: 'lob' },
  { name: 'LONGTEXT', primitiveType: 'lob' },
  { name: 'MEDIUMBLOB', primitiveType: 'lob' },
  { name: 'MEDIUMINT', primitiveType: 'int' },
  { name: 'MEDIUMTEXT', primitiveType: 'lob' },
  { name: 'MIDDLEINT', primitiveType: 'int' },
  { name: 'MULTILINESTRING', primitiveType: 'string' },
  { name: 'MULTIPOINT', primitiveType: 'string' },
  { name: 'MULTIPOLYGON', primitiveType: 'string' },
  { name: 'NATIONAL CHAR VARYING', primitiveType: 'string' },
  { name: 'NATIONAL CHAR', primitiveType: 'string' },
  { name: 'NATIONAL CHARACTER VARYING', primitiveType: 'string' },
  { name: 'NATIONAL CHARACTER', primitiveType: 'string' },
  { name: 'NATIONAL VARCHAR', primitiveType: 'string' },
  { name: 'NATIONAL VARCHARACTER', primitiveType: 'string' },
  { name: 'NCHAR VARCHAR', primitiveType: 'string' },
  { name: 'NCHAR VARCHARACTER', primitiveType: 'string' },
  { name: 'NCHAR VARYING', primitiveType: 'string' },
  { name: 'NCHAR', primitiveType: 'string' },
  { name: 'NUMBER', primitiveType: 'decimal' },
  { name: 'NUMERIC', primitiveType: 'decimal' },
  { name: 'NVARCHAR', primitiveType: 'string' },
  { name: 'POINT', primitiveType: 'string' },
  { name: 'POLYGON', primitiveType: 'string' },
  { name: 'RAW', primitiveType: 'string' },
  { name: 'REAL', primitiveType: 'double' },
  { name: 'SERIAL', primitiveType: 'long' },
  { name: 'SET', primitiveType: 'string' },
  { name: 'SMALLINT', primitiveType: 'int' },
  { name: 'SQL_TSI_YEAR', primitiveType: 'int' },
  { name: 'TEXT', primitiveType: 'lob' },
  { name: 'TIME', primitiveType: 'time' },
  { name: 'TIMESTAMP', primitiveType: 'dateTime' },
  { name: 'TINYBLOB', primitiveType: 'lob' },
  { name: 'TINYINT', primitiveType: 'int' },
  { name: 'TINYTEXT', primitiveType: 'lob' },
  { name: 'UUID', primitiveType: 'string' },
  { name: 'VARBINARY', primitiveType: 'string' },
  { name: 'VARCHAR', primitiveType: 'string' },
  { name: 'VARCHAR2', primitiveType: 'string' },
  { name: 'VARCHARACTER', primitiveType: 'string' },
  { name: 'VECTOR', primitiveType: 'string' },
  { name: 'XMLTYPE', primitiveType: 'lob' },
  { name: 'YEAR', primitiveType: 'int' },
];
