import { DataTypeHint } from '@/constants/sql/dataType';

/**
 * https://learn.microsoft.com/en-us/sql/t-sql/data-types/data-types-transact-sql
 */
export const MSSQLTypes: DataTypeHint[] = [
  { name: 'bigint', primitiveType: 'long' },
  { name: 'binary varying', primitiveType: 'string' },
  { name: 'binary', primitiveType: 'lob' },
  { name: 'bit', primitiveType: 'int' },
  { name: 'char varying', primitiveType: 'string' },
  { name: 'char', primitiveType: 'string' },
  { name: 'character varying', primitiveType: 'string' },
  { name: 'character', primitiveType: 'string' },
  { name: 'date', primitiveType: 'date' },
  { name: 'datetime', primitiveType: 'dateTime' },
  { name: 'datetime2', primitiveType: 'dateTime' },
  { name: 'datetimeoffset', primitiveType: 'dateTime' },
  { name: 'dec', primitiveType: 'decimal' },
  { name: 'decimal', primitiveType: 'decimal' },
  { name: 'double precision', primitiveType: 'double' },
  { name: 'float', primitiveType: 'double' },
  { name: 'geography', primitiveType: 'string' },
  { name: 'geometry', primitiveType: 'string' },
  { name: 'hierarchyid', primitiveType: 'string' },
  { name: 'image', primitiveType: 'lob' },
  { name: 'int', primitiveType: 'int' },
  { name: 'integer', primitiveType: 'int' },
  { name: 'json', primitiveType: 'lob' },
  { name: 'money', primitiveType: 'double' },
  { name: 'national char varying', primitiveType: 'string' },
  { name: 'national char', primitiveType: 'string' },
  { name: 'national character varying', primitiveType: 'string' },
  { name: 'national character', primitiveType: 'string' },
  { name: 'national text', primitiveType: 'lob' },
  { name: 'nchar', primitiveType: 'string' },
  { name: 'ntext', primitiveType: 'lob' },
  { name: 'numeric', primitiveType: 'float' },
  { name: 'nvarchar', primitiveType: 'string' },
  { name: 'real', primitiveType: 'float' },
  { name: 'rowversion', primitiveType: 'string' },
  { name: 'smalldatetime', primitiveType: 'dateTime' },
  { name: 'smallint', primitiveType: 'int' },
  { name: 'smallmoney', primitiveType: 'float' },
  { name: 'sql_variant', primitiveType: 'string' },
  { name: 'text', primitiveType: 'lob' },
  { name: 'time', primitiveType: 'time' },
  { name: 'timestamp', primitiveType: 'string' },
  { name: 'tinyint', primitiveType: 'int' },
  { name: 'uniqueidentifier', primitiveType: 'string' },
  { name: 'varbinary', primitiveType: 'string' },
  { name: 'varchar', primitiveType: 'string' },
  { name: 'vector', primitiveType: 'string' },
  { name: 'xml', primitiveType: 'lob' },
];
