import { DataTypeHint } from '@/constants/sql/dataType';

/**
 * https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/Data-Types.html
 */
export const OracleTypes: DataTypeHint[] = [
  { name: 'ANYDATA', primitiveType: 'string' },
  { name: 'BFILE', primitiveType: 'lob' },
  { name: 'BINARY_DOUBLE', primitiveType: 'double' },
  { name: 'BINARY_FLOAT', primitiveType: 'float' },
  { name: 'BLOB', primitiveType: 'lob' },
  { name: 'BOOL', primitiveType: 'boolean' },
  { name: 'BOOLEAN', primitiveType: 'boolean' },
  { name: 'CHAR VARYING', primitiveType: 'string' },
  { name: 'CHAR', primitiveType: 'string' },
  { name: 'CHARACTER VARYING', primitiveType: 'string' },
  { name: 'CHARACTER', primitiveType: 'string' },
  { name: 'CLOB', primitiveType: 'lob' },
  { name: 'DATE', primitiveType: 'date' },
  { name: 'DEC', primitiveType: 'decimal' },
  { name: 'DECIMAL', primitiveType: 'decimal' },
  { name: 'DOUBLE PRECISION', primitiveType: 'double' },
  { name: 'FLOAT', primitiveType: 'double' },
  { name: 'INT', primitiveType: 'int' },
  { name: 'INTEGER', primitiveType: 'int' },
  { name: 'INTERVAL DAY TO SECOND', primitiveType: 'time' },
  { name: 'INTERVAL YEAR TO MONTH', primitiveType: 'time' },
  { name: 'JSON', primitiveType: 'lob' },
  { name: 'LONG RAW', primitiveType: 'lob' },
  { name: 'LONG VARCHAR', primitiveType: 'lob' },
  { name: 'LONG', primitiveType: 'lob' },
  { name: 'NATIONAL CHAR VARYING', primitiveType: 'string' },
  { name: 'NATIONAL CHAR', primitiveType: 'string' },
  { name: 'NATIONAL CHARACTER VARYING', primitiveType: 'string' },
  { name: 'NATIONAL CHARACTER', primitiveType: 'string' },
  { name: 'NCHAR VARYING', primitiveType: 'string' },
  { name: 'NCHAR', primitiveType: 'string' },
  { name: 'NCLOB', primitiveType: 'lob' },
  { name: 'NUMBER', primitiveType: 'long' },
  { name: 'NUMERIC', primitiveType: 'decimal' },
  { name: 'NVARCHAR2', primitiveType: 'string' },
  { name: 'RAW', primitiveType: 'lob' },
  { name: 'REAL', primitiveType: 'float' },
  { name: 'ROWID', primitiveType: 'string' },
  { name: 'SDO_GEOMETRY', primitiveType: 'string' },
  { name: 'SDO_GEORASTER', primitiveType: 'string' },
  { name: 'SDO_TOPO_GEOMETRY', primitiveType: 'string' },
  { name: 'SMALLINT', primitiveType: 'int' },
  { name: 'TIMESTAMP WITH LOCAL TIME ZONE', primitiveType: 'dateTime' },
  { name: 'TIMESTAMP WITH TIME ZONE', primitiveType: 'dateTime' },
  { name: 'TIMESTAMP', primitiveType: 'dateTime' },
  { name: 'URIType', primitiveType: 'string' },
  { name: 'UROWID', primitiveType: 'string' },
  { name: 'VARCHAR', primitiveType: 'string' },
  { name: 'VARCHAR2', primitiveType: 'string' },
  { name: 'VECTOR', primitiveType: 'string' },
  { name: 'XMLType', primitiveType: 'string' },
];
