import { DataTypeHint } from '@/constants/sql/dataType';

/**
 * https://www.postgresql.org/docs/current/datatype.html
 */
export const PostgreSQLTypes: DataTypeHint[] = [
  { name: 'bigint', primitiveType: 'long' },
  { name: 'bigserial', primitiveType: 'long' },
  { name: 'bit varying', primitiveType: 'int' },
  { name: 'bit', primitiveType: 'int' },
  { name: 'bool', primitiveType: 'boolean' },
  { name: 'boolean', primitiveType: 'boolean' },
  { name: 'box', primitiveType: 'string' },
  { name: 'bpchar', primitiveType: 'string' },
  { name: 'bytea', primitiveType: 'string' },
  { name: 'char', primitiveType: 'string' },
  { name: 'character varying', primitiveType: 'string' },
  { name: 'character', primitiveType: 'string' },
  { name: 'cid', primitiveType: 'long' },
  { name: 'cidr', primitiveType: 'string' },
  { name: 'circle', primitiveType: 'string' },
  { name: 'date', primitiveType: 'date' },
  { name: 'datemultirange', primitiveType: 'string' },
  { name: 'daterange', primitiveType: 'string' },
  { name: 'decimal', primitiveType: 'decimal' },
  { name: 'double precision', primitiveType: 'double' },
  { name: 'float', primitiveType: 'double' },
  { name: 'float4', primitiveType: 'float' },
  { name: 'float8', primitiveType: 'double' },
  { name: 'inet', primitiveType: 'string' },
  { name: 'int', primitiveType: 'int' },
  { name: 'int2', primitiveType: 'int' },
  { name: 'int4', primitiveType: 'int' },
  { name: 'int4multirange', primitiveType: 'string' },
  { name: 'int4range', primitiveType: 'string' },
  { name: 'int8', primitiveType: 'long' },
  { name: 'int8multirange', primitiveType: 'string' },
  { name: 'int8range', primitiveType: 'string' },
  { name: 'integer', primitiveType: 'int' },
  { name: 'interval day to hour', primitiveType: 'time' },
  { name: 'interval day to minute', primitiveType: 'time' },
  { name: 'interval day to second', primitiveType: 'time' },
  { name: 'interval day', primitiveType: 'time' },
  { name: 'interval hour to minute', primitiveType: 'time' },
  { name: 'interval hour to second', primitiveType: 'time' },
  { name: 'interval hour', primitiveType: 'time' },
  { name: 'interval minute to second', primitiveType: 'time' },
  { name: 'interval minute', primitiveType: 'time' },
  { name: 'interval month', primitiveType: 'time' },
  { name: 'interval second', primitiveType: 'time' },
  { name: 'interval year to month', primitiveType: 'time' },
  { name: 'interval year', primitiveType: 'time' },
  { name: 'interval', primitiveType: 'time' },
  { name: 'json', primitiveType: 'lob' },
  { name: 'jsonb', primitiveType: 'lob' },
  { name: 'jsonpath', primitiveType: 'string' },
  { name: 'line', primitiveType: 'string' },
  { name: 'lseg', primitiveType: 'string' },
  { name: 'macaddr', primitiveType: 'string' },
  { name: 'macaddr8', primitiveType: 'string' },
  { name: 'money', primitiveType: 'double' },
  { name: 'name', primitiveType: 'string' },
  { name: 'numeric', primitiveType: 'decimal' },
  { name: 'nummultirange', primitiveType: 'string' },
  { name: 'numrange', primitiveType: 'string' },
  { name: 'oid', primitiveType: 'long' },
  { name: 'path', primitiveType: 'string' },
  { name: 'pg_lsn', primitiveType: 'int' },
  { name: 'pg_snapshot', primitiveType: 'string' },
  { name: 'point', primitiveType: 'string' },
  { name: 'polygon', primitiveType: 'string' },
  { name: 'real', primitiveType: 'float' },
  { name: 'regclass', primitiveType: 'string' },
  { name: 'regcollation', primitiveType: 'string' },
  { name: 'regconfig', primitiveType: 'string' },
  { name: 'regdictionary', primitiveType: 'string' },
  { name: 'regnamespace', primitiveType: 'string' },
  { name: 'regoper', primitiveType: 'string' },
  { name: 'regoperator', primitiveType: 'string' },
  { name: 'regproc', primitiveType: 'string' },
  { name: 'regprocedure', primitiveType: 'string' },
  { name: 'regrole', primitiveType: 'string' },
  { name: 'regtype', primitiveType: 'string' },
  { name: 'serial', primitiveType: 'int' },
  { name: 'serial2', primitiveType: 'int' },
  { name: 'serial4', primitiveType: 'int' },
  { name: 'serial8', primitiveType: 'long' },
  { name: 'smallint', primitiveType: 'int' },
  { name: 'smallserial', primitiveType: 'int' },
  { name: 'text', primitiveType: 'string' },
  { name: 'tid', primitiveType: 'string' },
  { name: 'time with time zone', primitiveType: 'time' },
  { name: 'time without time zone', primitiveType: 'time' },
  { name: 'time', primitiveType: 'time' },
  { name: 'timestamp with time zone', primitiveType: 'dateTime' },
  { name: 'timestamp without time zone', primitiveType: 'dateTime' },
  { name: 'timestamp', primitiveType: 'dateTime' },
  { name: 'timestamptz', primitiveType: 'dateTime' },
  { name: 'timetz', primitiveType: 'time' },
  { name: 'tsmultirange', primitiveType: 'string' },
  { name: 'tsquery', primitiveType: 'string' },
  { name: 'tsrange', primitiveType: 'string' },
  { name: 'tstzmultirange', primitiveType: 'string' },
  { name: 'tstzrange', primitiveType: 'string' },
  { name: 'tsvector', primitiveType: 'string' },
  { name: 'txid_snapshot', primitiveType: 'string' },
  { name: 'uuid', primitiveType: 'string' },
  { name: 'varbit', primitiveType: 'int' },
  { name: 'varchar', primitiveType: 'string' },
  { name: 'xid', primitiveType: 'long' },
  { name: 'xid8', primitiveType: 'long' },
  { name: 'xml', primitiveType: 'lob' },
];
