import { DataTypeHint } from '@/constants/sql/dataType';

/**
 * https://docs.snowflake.com/en/sql-reference-data-types
 */
export const SnowflakeTypes: DataTypeHint[] = [
  { name: 'ARRAY', primitiveType: 'string' },
  { name: 'BIGINT', primitiveType: 'long' },
  { name: 'BINARY', primitiveType: 'lob' },
  { name: 'BOOLEAN', primitiveType: 'boolean' },
  { name: 'BYTEINT', primitiveType: 'int' },
  { name: 'CHAR VARYING', primitiveType: 'string' },
  { name: 'CHAR', primitiveType: 'string' },
  { name: 'CHARACTER', primitiveType: 'string' },
  { name: 'DATE', primitiveType: 'date' },
  { name: 'DATETIME', primitiveType: 'dateTime' },
  { name: 'DEC', primitiveType: 'decimal' },
  { name: 'DECFLOAT', primitiveType: 'decimal' },
  { name: 'DECIMAL', primitiveType: 'decimal' },
  { name: 'DOUBLE PRECISION', primitiveType: 'double' },
  { name: 'DOUBLE', primitiveType: 'double' },
  { name: 'FILE', primitiveType: 'string' },
  { name: 'FLOAT', primitiveType: 'double' },
  { name: 'FLOAT4', primitiveType: 'double' },
  { name: 'FLOAT8', primitiveType: 'double' },
  { name: 'GEOGRAPHY', primitiveType: 'string' },
  { name: 'GEOMETRY', primitiveType: 'string' },
  { name: 'INT', primitiveType: 'int' },
  { name: 'INTEGER', primitiveType: 'int' },
  { name: 'MAP', primitiveType: 'string' },
  { name: 'NCHAR VARYING', primitiveType: 'string' },
  { name: 'NCHAR', primitiveType: 'string' },
  { name: 'NUMBER', primitiveType: 'long' },
  { name: 'NUMERIC', primitiveType: 'decimal' },
  { name: 'NVARCHAR', primitiveType: 'string' },
  { name: 'NVARCHAR2', primitiveType: 'string' },
  { name: 'OBJECT', primitiveType: 'string' },
  { name: 'REAL', primitiveType: 'double' },
  { name: 'SMALLINT', primitiveType: 'int' },
  { name: 'STRING', primitiveType: 'string' },
  { name: 'TEXT', primitiveType: 'string' },
  { name: 'TIME', primitiveType: 'time' },
  { name: 'TIMESTAMP WITH LOCAL TIME ZONE', primitiveType: 'dateTime' },
  { name: 'TIMESTAMP WITH TIME ZONE', primitiveType: 'dateTime' },
  { name: 'TIMESTAMP WITHOUT TIME ZONE', primitiveType: 'dateTime' },
  { name: 'TIMESTAMP_LTZ', primitiveType: 'dateTime' },
  { name: 'TIMESTAMP_NTZ', primitiveType: 'dateTime' },
  { name: 'TIMESTAMP_TZ', primitiveType: 'dateTime' },
  { name: 'TIMESTAMP', primitiveType: 'dateTime' },
  { name: 'TIMESTAMPLTZ', primitiveType: 'dateTime' },
  { name: 'TIMESTAMPNTZ', primitiveType: 'dateTime' },
  { name: 'TIMESTAMPTZ', primitiveType: 'dateTime' },
  { name: 'TINYINT', primitiveType: 'int' },
  { name: 'UNKNOWN', primitiveType: 'string' },
  { name: 'UUID', primitiveType: 'string' },
  { name: 'VARBINARY', primitiveType: 'lob' },
  { name: 'VARCHAR', primitiveType: 'string' },
  { name: 'VARCHAR2', primitiveType: 'string' },
  { name: 'VARIANT', primitiveType: 'string' },
  { name: 'VECTOR', primitiveType: 'string' },
];
