/**
 * https://learn.microsoft.com/en-us/sql/t-sql/data-types/data-types-transact-sql
 */
export const MSSQLTypes: string[] = [
  'BIGINT',
  'BINARY VARYING',
  'BINARY',
  'BIT',
  'CHAR VARYING',
  'CHAR',
  'CHARACTER VARYING',
  'CHARACTER',
  'DATE',
  'DATETIME',
  'DATETIME2',
  'DATETIMEOFFSET',
  'DEC',
  'DECIMAL',
  'DOUBLE PRECISION',
  'FLOAT',
  'GEOGRAPHY',
  'GEOMETRY',
  'HIERARCHYID',
  'IMAGE',
  'INT',
  'INTEGER',
  'JSON',
  'MONEY',
  'NATIONAL CHAR VARYING',
  'NATIONAL CHAR',
  'NATIONAL CHARACTER VARYING',
  'NATIONAL CHARACTER',
  'NATIONAL TEXT',
  'NCHAR',
  'NTEXT',
  'NUMERIC',
  'NVARCHAR',
  'REAL',
  'ROWVERSION',
  'SMALLDATETIME',
  'SMALLINT',
  'SMALLMONEY',
  'SQL_VARIANT',
  'TEXT',
  'TIME',
  'TIMESTAMP',
  'TINYINT',
  'UNIQUEIDENTIFIER',
  'VARBINARY',
  'VARCHAR',
  'VECTOR',
  'XML',
];
