
CREATE SCHEMA IF NOT EXISTS shop;
SET search_path TO shop, public;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS member
(
  id    INT          NOT NULL GENERATED ALWAYS AS IDENTITY,
  email VARCHAR(255) NOT NULL UNIQUE,
  PRIMARY KEY (id)
);

COMMENT ON TABLE member IS 'Members';

CREATE TABLE IF NOT EXISTS post
(
  id        INT          NOT NULL GENERATED ALWAYS AS IDENTITY,
  member_id INT          NOT NULL,
  title     VARCHAR(200) NOT NULL,
  PRIMARY KEY (id)
);

ALTER TABLE post DROP CONSTRAINT IF EXISTS FK_member_TO_post;
ALTER TABLE post
  ADD CONSTRAINT FK_member_TO_post
    FOREIGN KEY (member_id)
    REFERENCES member (id)
    ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_post_title
  ON post (title ASC);

GRANT SELECT ON member, post TO PUBLIC;
