
ALTER SESSION SET CURRENT_SCHEMA = shop;

CREATE TABLE member
(
  id    INT          NOT NULL,
  email VARCHAR(255) NOT NULL,
  CONSTRAINT PK_member PRIMARY KEY (id)
);

ALTER TABLE member
  ADD CONSTRAINT UQ_member_email UNIQUE (email);

CREATE SEQUENCE SEQ_member
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER SEQ_TRG_member
BEFORE INSERT ON member
REFERENCING NEW AS NEW FOR EACH ROW
BEGIN
  SELECT SEQ_member.NEXTVAL
  INTO :NEW.id
  FROM DUAL;
END;
/

COMMENT ON TABLE member IS 'Members';

CREATE TABLE post
(
  id        INT          NOT NULL,
  member_id INT          NOT NULL,
  title     VARCHAR(200) NOT NULL,
  CONSTRAINT PK_post PRIMARY KEY (id)
);

CREATE SEQUENCE SEQ_post
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER SEQ_TRG_post
BEFORE INSERT ON post
REFERENCING NEW AS NEW FOR EACH ROW
BEGIN
  SELECT SEQ_post.NEXTVAL
  INTO :NEW.id
  FROM DUAL;
END;
/

ALTER TABLE post
  ADD CONSTRAINT FK_member_TO_post
    FOREIGN KEY (member_id)
    REFERENCES member (id)
    ON DELETE CASCADE;

CREATE INDEX idx_post_title
  ON post (title ASC);
