import { DataTypeHint } from "../DataType";

/**
 * https://www.postgresql.org/docs/current/datatype.html
 */
export const PostgreSQLTypes: DataTypeHint[] = [
  { name: "bigint", primitiveType: "long" },
  { name: "int8", primitiveType: "long" },
  { name: "bigserial", primitiveType: "long" },
  { name: "serial8", primitiveType: "long" },
  { name: "bit", primitiveType: "int" },
  { name: "bit varying", primitiveType: "int" },
  { name: "varbit", primitiveType: "int" },
  { name: "boolean", primitiveType: "boolean" },
  { name: "bool", primitiveType: "boolean" },
  { name: "box", primitiveType: "string" },
  { name: "bytea", primitiveType: "string" },
  { name: "character", primitiveType: "string" },
  { name: "char", primitiveType: "string" },
  { name: "character varying", primitiveType: "string" },
  { name: "varchar", primitiveType: "string" },
  { name: "cidr", primitiveType: "string" },
  { name: "circle", primitiveType: "string" },
  { name: "date", primitiveType: "date" },
  { name: "double precision", primitiveType: "double" },
  { name: "float8", primitiveType: "double" },
  { name: "inet", primitiveType: "string" },
  { name: "integer", primitiveType: "int" },
  { name: "int", primitiveType: "int" },
  { name: "int4", primitiveType: "int" },
  { name: "interval", primitiveType: "time" },
  { name: "json", primitiveType: "lob" },
  { name: "jsonb", primitiveType: "lob" },
  { name: "line", primitiveType: "string" },
  { name: "lseg", primitiveType: "string" },
  { name: "macaddr", primitiveType: "string" },
  { name: "macaddr8", primitiveType: "string" },
  { name: "money", primitiveType: "double" },
  { name: "numeric", primitiveType: "decimal" },
  { name: "decimal", primitiveType: "decimal" },
  { name: "path", primitiveType: "string" },
  { name: "pg_lsn", primitiveType: "int" },
  { name: "point", primitiveType: "string" },
  { name: "polygon", primitiveType: "string" },
  { name: "real", primitiveType: "float" },
  { name: "float4", primitiveType: "float" },
  { name: "smallint", primitiveType: "int" },
  { name: "int2", primitiveType: "int" },
  { name: "smallserial", primitiveType: "int" },
  { name: "serial2", primitiveType: "int" },
  { name: "serial", primitiveType: "int" },
  { name: "serial4", primitiveType: "int" },
  { name: "text", primitiveType: "string" },
  { name: "time", primitiveType: "time" },
  { name: "time with time zone", primitiveType: "time" },
  { name: "timetz", primitiveType: "time" },
  { name: "timestamp", primitiveType: "dateTime" },
  { name: "timestamp with time zone", primitiveType: "dateTime" },
  { name: "timestamptz", primitiveType: "dateTime" },
  { name: "tsquery", primitiveType: "string" },
  { name: "tsvector", primitiveType: "string" },
  { name: "txid_snapshot", primitiveType: "string" },
  { name: "uuid", primitiveType: "string" },
  { name: "xml", primitiveType: "lob" },
];
