import { describe, expect, it } from 'vite-plus/test';

import { RefPos, StatementType } from '@/parser/statement';
import { alterTableAlterColumnParser } from '@/parser/statement/alter.table.alter.column';
import { tokenizer } from '@/parser/tokenizer';

// Parses source, which opens with the statement, and names the token the
// cursor stops on, '' at the end of the source.
const parse = (source: string) => {
  const tokens = tokenizer(source);
  const $pos: RefPos = { value: 0 };
  const ast = alterTableAlterColumnParser(tokens, $pos);
  return { ast, stop: tokens[$pos.value]?.value ?? '' };
};

const autoIncrement = (name: string, columnName: string) => ({
  type: StatementType.alterTableAlterColumnAutoIncrement,
  name,
  columnName,
});

describe('alterTableAlterColumnParser', () => {
  it("reads the nextval default pg_dump sets apart from a serial column's table", () => {
    const { ast, stop } = parse(
      "ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);\n" +
        'CREATE TABLE x (a INT);'
    );

    expect(ast).toEqual([autoIncrement('users', 'id')]);
    expect(stop).toBe('CREATE');
  });

  it('reads the identity pg_dump adds to a column with its sequence options', () => {
    const { ast, stop } = parse(
      'ALTER TABLE public.items ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (\n' +
        '    SEQUENCE NAME public.items_id_seq\n' +
        '    START WITH 1\n' +
        '    INCREMENT BY 1\n' +
        '    NO MINVALUE\n' +
        '    NO MAXVALUE\n' +
        '    CACHE 1\n' +
        ');\n' +
        "COMMENT ON TABLE public.items IS 'x';"
    );

    expect(ast).toEqual([autoIncrement('items', 'id')]);
    expect(stop).toBe('COMMENT');
  });

  it.each<[string, string, string]>([
    [
      'ALTER TABLE t ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;',
      't',
      'Id',
    ],
    ["ALTER TABLE ONLY t ALTER c SET DEFAULT (nextval('s'));", 't', 'c'],
    [
      'ALTER TABLE ONLY "public"."Orders" ALTER COLUMN "Id" SET DEFAULT nextval(\'public."Orders_Id_seq"\'::regclass);',
      'Orders',
      'Id',
    ],
    ["ALTER TABLE only ALTER COLUMN c SET DEFAULT nextval('s');", 'only', 'c'],
    [
      "ALTER TABLE ONLY public.t ALTER COLUMN id SET DEFAULT nextval(('public.t_id_seq'::text)::regclass);",
      't',
      'id',
    ],
    [
      'ALTER TABLE ONLY "public"."users" ALTER COLUMN "id" SET DEFAULT "nextval"(\'"public"."users_id_seq"\'::"regclass");',
      'users',
      'id',
    ],
    [
      "ALTER TABLE ONLY public.t ALTER COLUMN delete SET DEFAULT nextval('public.t_delete_seq'::regclass);",
      't',
      'delete',
    ],
    ["ALTER TABLE t ALTER alter SET DEFAULT nextval('s');", 't', 'alter'],
    [
      'ALTER TABLE t ALTER COLUMN drop ADD GENERATED BY DEFAULT AS IDENTITY;',
      't',
      'drop',
    ],
  ])('reads %s', (source, name, columnName) => {
    expect(parse(source).ast).toEqual([autoIncrement(name, columnName)]);
  });

  it.each<string>([
    'ALTER TABLE ONLY t ALTER COLUMN c SET DEFAULT 0;',
    "ALTER TABLE ONLY t ALTER COLUMN c SET DEFAULT nextval('s') + 1;",
    'ALTER TABLE ONLY t ALTER c SET DEFAULT (nextval(s));',
    'ALTER TABLE t ALTER COLUMN c SET DEFAULT (NEXTVAL(shop.order_seq));',
    'ALTER TABLE t ALTER COLUMN c SET DEFAULT NEXT VALUE FOR s;',
    'ALTER TABLE t ALTER COLUMN c SET NOT NULL;',
    'ALTER TABLE t ALTER COLUMN c DROP DEFAULT;',
    'ALTER TABLE t ALTER COLUMN c SET GENERATED ALWAYS;',
    'ALTER TABLE t ALTER COLUMN c TYPE bigint;',
    'ALTER TABLE t ALTER COLUMN c ADD GENERATED ALWAYS AS (a + 1) STORED;',
    'ALTER TABLE t ALTER COLUMN c ADD GENERATED ALWAYS AS',
    'ALTER TABLE t ALTER COLUMN c "SET" DEFAULT nextval(\'s\');',
    'ALTER TABLE t ALTER COLUMN delete DROP DEFAULT;',
    'ALTER TABLE t ALTER COLUMN;',
    'ALTER TABLE t ALTER COLUMN c',
    'ALTER TABLE t ALTER COLUMN',
    'ALTER TABLE t ALTER',
  ])('reads no auto increment out of %s', source => {
    const { ast, stop } = parse(`${source}\nCREATE TABLE x (a INT);`);

    expect(ast).toEqual([]);
    expect(stop).toBe('CREATE');
  });

  it('reads every action of the list that makes its column auto increment', () => {
    const { ast, stop } = parse(
      'ALTER TABLE t\n' +
        '  ALTER COLUMN a DROP DEFAULT,\n' +
        "  ALTER COLUMN b SET DEFAULT nextval('t_b_seq'::regclass),\n" +
        '  ADD CONSTRAINT ck CHECK (a IN (1, 2)),\n' +
        '  ALTER COLUMN c ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 1),\n' +
        "  ALTER COLUMN d SET DEFAULT lower('a', 'b');\n" +
        'CREATE TABLE x (a INT);'
    );

    expect(ast).toEqual([autoIncrement('t', 'b'), autoIncrement('t', 'c')]);
    expect(stop).toBe('CREATE');
  });

  it('ends the statement at the next one when no semicolon does', () => {
    const { ast, stop } = parse(
      "ALTER TABLE t ALTER COLUMN a SET DEFAULT nextval('s')\n" +
        'ALTER TABLE t ALTER COLUMN b SET DEFAULT 0\n' +
        'DROP TABLE x'
    );

    expect(ast).toEqual([autoIncrement('t', 'a')]);
    expect(stop).toBe('ALTER');
  });

  it('reads an ALTER after anything but a comma as the next statement', () => {
    const { ast, stop } = parse(
      'ALTER TABLE t ALTER COLUMN a SET NOT NULL, ADD CONSTRAINT ck CHECK (a > 0) ALTER TABLE u ALTER COLUMN b ADD GENERATED ALWAYS AS IDENTITY'
    );

    expect(ast).toEqual([]);
    expect(stop).toBe('ALTER');
  });

  it('reads an ALTER TABLE after a comma as the next statement', () => {
    const tokens = tokenizer(
      'ALTER TABLE t ALTER COLUMN a DROP NOT NULL,\n' +
        'ALTER TABLE u ALTER COLUMN b ADD GENERATED ALWAYS AS IDENTITY;'
    );
    const $pos: RefPos = { value: 0 };

    expect(alterTableAlterColumnParser(tokens, $pos)).toEqual([]);
    expect(
      tokens.slice($pos.value, $pos.value + 3).map(({ value }) => value)
    ).toEqual(['ALTER', 'TABLE', 'u']);
  });

  it.each<[string, string[]]>([
    [
      'ALTER TABLE t ALTER\nALTER TABLE u ADD PRIMARY KEY (id);',
      ['ALTER', 'TABLE', 'u'],
    ],
    [
      "ALTER TABLE t ALTER COLUMN\nCOMMENT ON TABLE t IS 'x';",
      ['COMMENT', 'ON', 'TABLE'],
    ],
    ['ALTER TABLE t ALTER COLUMN\nDROP TABLE u;', ['DROP', 'TABLE', 'u']],
  ])(
    'reads no column name out of the statement word that opens the next statement in %s',
    (source, next) => {
      const tokens = tokenizer(source);
      const $pos: RefPos = { value: 0 };

      expect(alterTableAlterColumnParser(tokens, $pos)).toEqual([]);
      expect(
        tokens.slice($pos.value, $pos.value + 3).map(({ value }) => value)
      ).toEqual(next);
    }
  );

  it('reads a statement cut off at the end of the source', () => {
    expect(parse('ALTER TABLE t ALTER COLUMN c').ast).toEqual([]);
    expect(
      parse("ALTER TABLE t ALTER COLUMN c SET DEFAULT nextval('s'")
    ).toEqual({ ast: [], stop: '' });
  });
});
